### ISSUE TITLE
Tests are failing

### ISSUE THREAD

**Issue by teolemon** [openfoodfacts/openbeautyfacts-ruby#31]
Finished in 31.524957s, 1.1420 runs/s, 2.1570 assertions/s.
  1) Failure:
TestOpenbeautyfacts#test_it_fetches_period_after_openings [/home/travis/build/openfoodfacts/openbeautyfacts-ruby/test/test_openbeautyfacts.rb:294]:
Expected [] to include "12 months".
  2) Failure:
TestOpenbeautyfacts#test_it_fetches_period_after_openings_for_locale [/home/travis/build/openfoodfacts/openbeautyfacts-ruby/test/test_openbeautyfacts.rb:301]:
Expected [] to include "12 mois".
  3) Failure:
TestOpenbeautyfacts#test_it_fetches_locales [/home/travis/build/openfoodfacts/openbeautyfacts-ruby/test/test_openbeautyfacts.rb:16]:
Expected [] to include "gd".

**Comment by nicolasleger** [comment]
Thanks ! CI is now fixed by https://github.com/openfoodfacts/openbeautyfacts-ruby/pull/38

However @teolemon the page https://fr.openbeautyfacts.org/durees-d-utilisation-apres-ouverture is unreachable but still linked in https://fr.openbeautyfacts.org/duree-d-utilisation-apres-ouverture/12-mois for example.
